CREATE TABLE IF NOT EXISTS emails (
	id BIGSERIAL PRIMARY KEY,
	data VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS contacts (
	id BIGSERIAL PRIMARY KEY,
	data VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS national_identity_card_numbers (
	id BIGSERIAL PRIMARY KEY,
	data VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS countries (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(250) NOT NULL UNIQUE,
	code NUMERIC(3) NOT NULL,
	currency VARCHAR(3) NOT NULL,
	currency_symbol VARCHAR(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS cities (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(250) NOT NULL,
	zip_code VARCHAR(8) NOT NULL,
	country_id BIGINT REFERENCES countries(id)
);

CREATE TABLE IF NOT EXISTS addresses (
	id BIGSERIAL PRIMARY KEY,
	country_id BIGINT REFERENCES countries(id),
	city_id BIGINT REFERENCES cities(id),
	street VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS persons (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(250),
	contact_id BIGINT REFERENCES contacts(id) UNIQUE
); 

CREATE TABLE IF NOT EXISTS users (
	id BIGSERIAL PRIMARY KEY,
	person_id BIGSERIAL REFERENCES persons(id),
	age NUMERIC(3) NOT NULL,
	address_id BIGINT REFERENCES addresses(id),
	email_id BIGINT REFERENCES emails(id) UNIQUE,
	national_identity_card_number_id BIGINT REFERENCES national_identity_card_numbers(id) UNIQUE
);

CREATE TABLE IF NOT EXISTS businesses (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR (250) NOT NULL UNIQUE,
	address_id BIGINT REFERENCES addresses(id),
	email_id BIGINT REFERENCES emails(id),
	contact_id BIGINT REFERENCES contacts(id)
);

CREATE TABLE IF NOT EXISTS branch (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR (250) NOT NULL UNIQUE,
	address_id BIGINT REFERENCES addresses(id),
	email_id BIGINT REFERENCES emails(id),
	contact_id BIGINT REFERENCES contacts(id)
);

CREATE TABLE IF NOT EXISTS job_names (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS companies_names (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(250) UNIQUE
);

CREATE TABLE IF NOT EXISTS item_names (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(250) UNIQUE
);

CREATE TABLE IF NOT EXISTS items (
	id BIGSERIAL PRIMARY KEY,
	item_name_id BIGINT REFERENCES item_names(id),
	company_name_id BIGINT REFERENCES companies_names(id),
	specifications JSON
);

CREATE TABLE IF NOT EXISTS prices (
	id BIGSERIAL PRIMARY KEY,
	prices JSON NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory (
	id BIGSERIAL PRIMARY KEY,
	item_id BIGINT REFERENCES items(id),
	price_id BIGINT REFERENCES prices(id),
	quantity NUMERIC NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sales (
	id BIGSERIAL PRIMARY KEY,
	item_id BIGINT REFERENCES items(id),
	price NUMERIC NOT NULL DEFAULT 0,
	seller BIGINT REFERENCES persons (id),
	buyer BIGINT REFERENCES persons (id)
);

CREATE TABLE IF NOT EXISTS purchases (
	id BIGSERIAL PRIMARY KEY,
	item_id BIGINT REFERENCES items(id),
	price NUMERIC NOT NULL DEFAULT 0,
	seller BIGINT REFERENCES persons (id),
	buyer BIGINT REFERENCES persons (id)
);

















